site_name: Python Pinterest Docs
site_description: Docs for Python Pinterest
repo_url: https://github.com/sns-sdks/python-pinterest
copyright: Copyright &copy; 2022 Ikaros kun

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: index.md
  - Installation: installation.md
  - Authorization: authorization.md
  - Usage: usage.md
  - Changelog: CHANGELOG.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realllkk520
    - icon: fontawesome/brands/github
      link: https://github.com/sns-sdks/python-pinterest


markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji