site_name: Mod Docs
site_description: Docs for Mod
repo_url: https://github.com/MerleLiuKun/PyModuleRepo
copyright: Copyright &copy; 2021 Ikaros kun

theme:
  name: material
  features:
    - navigation.tabs
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

nav:
  - Introduction: index.md

extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/realllkk520
    - icon: fontawesome/brands/github
      link: https://github.com/MerleLiuKun/PyModuleRepo


markdown_extensions:
  - codehilite
  - admonition
  - pymdownx.superfences
  - pymdownx.emoji